apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podinfo
  name: podinfo
spec:
  replicas: 0
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - image: stefanprodan/podinfo
        name: podinfo
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
type: Opaque
data:
  password: cGFzc3cwcmQh
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-elasticsearch-secret
spec:
  secretTargetRef:
  - parameter: password
    name: elasticsearch-secrets
    key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: elasticsearch-scaledobject
spec:
  minReplicaCount: 1 # 0 means no minReplicaCount
  maxReplicaCount: 5 
  idleReplicaCount: 0 
  pollingInterval: 3 # 3 means 3 seconds This is the interval to check each trigger on the scaled object
  cooldownPeriod:  30 # 30 means 30 seconds This is the cooldown period after a scale up or down
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo # Mandatory. Must be in the same namespace as the ScaledObject
  triggers:
    - type: elasticsearch
      metadata:
        addresses: "http://elasticsearch-svc.elasticsearch.svc.cluster.local:9200"
        username: "elastic"
        index: keda
        searchTemplateName: keda-search-template
        valueLocation: "hits.total.value"
        targetValue: "1"
        parameters: "dummy_value:1;dumb_value:oOooo"
      authenticationRef:
        name: keda-trigger-auth-elasticsearch-secret
